---
# tasks file for docker
  - name: install needed dependencies
    become: yes
    apt:
      force_apt_get: yes
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
      update_cache: yes
      state: present

  - name: install OpenPGP
    shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg

  - name: install apt-key
    become: yes
    apt_key:
      keyserver: https://download.docker.com/linux/ubuntu/gpg
      id: 0EBFCD88

  - name: add docker repository
    become: yes
    apt_repository:
      repo: "deb https://download.docker.com/linux/ubuntu {{docker_ubuntu_version}} stable"
      state: present

  - name: install docker
    become: yes
    apt:
      force_apt_get: yes
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes
      state: present

  - name: install docker-compose
    become: yes
    shell: curl -L "https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

  - name: change docker-compose dir access rights
    become: yes
    shell: chmod +x /usr/local/bin/docker-compose

  - name: ensure group "docker" exists
    group:
      name: docker
      state: present

  - name: add current user to the group
    become: yes
    user:
      name: "{{hostvars['infra_server'].ansible_user}}"
      shell: /bin/bash
      groups: docker
      append: yes

  - name: unconditionally reboot the machine with all defaults
    become: yes
    reboot: