all:
  hosts:
    infra_server:
      ansible_host: 192.168.1.68
      ansible_connection: ssh
      ansible_ssh_pass: your_ssh_pasword
      ansible_user: dminchuk
      ansible_become_pass: your_sudo_password
#infra_server ansible_host=192.168.1.68 ansible_connection=ssh ansible_ssh_pass=rT8lCAD3 ansible_user=dminchuk ansible_become_pass=rT8lCAD3